<template>
  <header>
    <nav>
      <!-- <ul>
        <li>
          <button @click="setActivePage('teams-list')">Teams</button>
        </li>
        <li>
          <button @click="setActivePage('users-list')">Users</button>
        </li>
      </ul> -->
<!-- now we navigate with routers -->
        <ul>
        <li>
          <!-- this router-link is a built in vue feature that helps us navigate these routes, like a special <a> tag -->
          <router-link to="/teams">Teams</router-link>
        </li>
        <li>
          <!-- to is the prop of the url that you are naviagting to that is linked in the routes in main.js -->
          <router-link to="/users">Users</router-link>
        </li>
      </ul>
    </nav>
  </header>
</template>

<script>
export default {
  // emits: ['set-page'],
  // methods: {
  //   setActivePage(page) {
  //     this.$emit('set-page', page);
  //   },
  // },
};
</script>

<style scoped>
header {
  width: 100%;
  height: 5rem;
  background-color: #11005c;
}

nav {
  height: 100%;
}

ul {
  list-style: none;
  margin: 0;
  padding: 0;
  height: 100%;
  display: flex;
  justify-content: center;
  align-items: center;
}

li {
  margin: 0 2rem;
}

/* this is the router-link bc vue renders it as a  */
a {
  text-decoration: none;
  font: inherit;
  background: transparent;
  border: 1px solid transparent;
  cursor: pointer;
  color: white;
  padding: 0.5rem 1.5rem;
  display: inline-block;
}

a:hover,
a:active,
a.router-link-active, a.active{
  color: #f1a80a;
  border-color: #f1a80a;
  background-color: #1a037e;
}
/* the router-active class is a special dynamic class generated by vue on the active router link */
</style>